//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeAutomation.db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeAutomationDbEntities : DbContext
    {
        public HomeAutomationDbEntities()
            : base("name=HomeAutomationDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<action> actions { get; set; }
        public virtual DbSet<component> components { get; set; }
        public virtual DbSet<control_panel> control_panel { get; set; }
        public virtual DbSet<datum> data { get; set; }
        public virtual DbSet<permission> permissions { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<scheduler> schedulers { get; set; }
        public virtual DbSet<switch_condition> switch_condition { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_group> user_group { get; set; }
    }
}
