//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeAutomation.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDatabaseDetail
    {
        public int idUsersDatabaseDetails { get; set; }
        public string databaseNameUsersDatabaseDetails { get; set; }
        public string ipAddressUsersDatabaseDetails { get; set; }
        public string portUsersDatabaseDetailsl { get; set; }
        public string dbUserUsersDatabaseDetails { get; set; }
        public string passwordUsersDatabaseDetails { get; set; }
    }
}
